# Generated by Django 5.1.1 on 2024-10-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_branchstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customername',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
